### ISSUE TITLE
Finir les avancements de rang

### ISSUE THREAD

**Issue by H2WO4** [PopolWorld/PopolPack#2]
Problème : Il faut une liste complète des rangs

**Comment by H2WO4** [comment]
Ne sera pas fait pour la première version

**Comment by NathanFallet** [comment]
@H2WO4 Que veux tu dire par liste des rangs ?

**Comment by H2WO4** [comment]
Savoir quels rang il y a, par exemple
Rang 1, nom : ___
Rang 2, nom : ___
Et surtout savoir combien de rangs il y a au total

**Comment by NathanFallet** [comment]
Cette partie là sera gérée par le plugin avec la PopolMoney pour upgrade. Que souhaitais tu ajouter dessus ?

**Comment by H2WO4** [comment]
Avoir des avancement et les gagner quand on monte de rang
C'est purement cosmétique, mais je pense que ça aide à intégrer toutes les features du serveur dans le vanilla de Minecraft

**Comment by NathanFallet** [comment]
Je vois. Quand la liste sera faite tu l'aura aussi, et tu me diras comment depuis le plugin je peux unlock les achievements en question (via un id, une commande ou je sais pas trop)
